/**
 * NFC slug parity tests — must match the Python twin
 * (ThaqalaynDataGenerator/app/words/normalize.py + its fixture test).
 *
 * The fixture `word-normalize.fixture.json` is a copy of the same file
 * the Python tests load. If the Python normalize.py changes, regenerate
 * the fixture and re-copy.
 */
import fixture from './word-normalize.fixture.json';
import { normalizeForMatch, slug } from './word-normalize';

describe('word-normalize.slug', () => {
  it('returns empty string for nullish input', () => {
    expect(slug('')).toBe('');
    expect(slug(null as unknown as string)).toBe('');
    expect(slug(undefined as unknown as string)).toBe('');
  });

  it('trims whitespace', () => {
    expect(slug('  قَالَ  ')).toBe('قَالَ');
    expect(slug('\tقَالَ\n')).toBe('قَالَ');
  });

  it('preserves diacritics (does not strip)', () => {
    expect(slug('قَالَ')).toBe('قَالَ');
    expect(slug('قَالُ')).toBe('قَالُ');
    expect(slug('قَالَ')).not.toBe(slug('قَالُ'));
  });

  it('produces byte-identical output to the Python twin on the shared fixture', () => {
    // The fixture is generated by the Python side via
    // unicodedata.normalize("NFC", input.strip()) and committed.
    // We assert TypeScript's normalize('NFC') produces the same bytes.
    let mismatches = 0;
    for (const entry of fixture as Array<{ input: string; nfc: string }>) {
      const got = slug(entry.input);
      if (got !== entry.nfc) {
        mismatches++;
        // Log up to 5 mismatches for diagnosis.
        if (mismatches <= 5) {
          // eslint-disable-next-line no-console
          console.error('NFC mismatch', {
            input: entry.input,
            expected_py: entry.nfc,
            got_ts: got,
            input_codepoints: [...entry.input].map((c) => c.charCodeAt(0).toString(16)),
            expected_codepoints: [...entry.nfc].map((c) => c.charCodeAt(0).toString(16)),
            got_codepoints: [...got].map((c) => c.charCodeAt(0).toString(16)),
          });
        }
      }
    }
    expect(mismatches).toBe(0);
    // Sanity: ensure fixture is non-empty.
    expect((fixture as unknown[]).length).toBeGreaterThan(100);
  });
});

describe('word-normalize.normalizeForMatch', () => {
  it('returns empty for nullish input', () => {
    expect(normalizeForMatch('')).toBe('');
    expect(normalizeForMatch(null as unknown as string)).toBe('');
  });

  it('strips diacritics', () => {
    expect(normalizeForMatch('قَالَ')).toBe('قال');
    expect(normalizeForMatch('مُحَمَّدٌ')).toBe('محمد');
  });

  it('unifies alif variants', () => {
    expect(normalizeForMatch('أحمد')).toBe('احمد');
    expect(normalizeForMatch('إبراهيم')).toBe('ابراهيم');
    expect(normalizeForMatch('آدم')).toBe('ادم');
  });

  it('unifies ya variants', () => {
    // ى (alif maksura) → ي
    expect(normalizeForMatch('على')).toBe('علي');
  });

  it('unifies ta marbuta to ha', () => {
    expect(normalizeForMatch('مكة')).toBe('مكه');
  });

  it('strips tatweel', () => {
    expect(normalizeForMatch('قاــــــل')).toBe('قال');
  });

  it('preserves non-Arabic characters', () => {
    expect(normalizeForMatch('hello قَالَ world')).toBe('hello قال world');
  });
});
